# Generated by Django 6.0.3 on 2026-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
